### ISSUE TITLE
Cannot build in xcode 10.1, 

### ISSUE THREAD

**Issue by ThematicaDigital** [RevenueCat/purchases-unity#11]
Unity build without errors, but in xcode i have this error:
![photo_2019-04-18_18-02-55](https://user-images.githubusercontent.com/46710232/56349830-5b242f00-6204-11e9-9170-f9fa380b6b56.jpg)

StoreKit is added.
unity 2018.3.10
No problem on xcode 10.2.

**Comment by rkotzy** [comment]
Going to mark this as closed since the solution is to upgrade to XCode 10.2

**Comment by Bfgeshka** [comment]
Upgrading XCode is not always a viable solution for technical reasons.

I personally cannot use revenuecat solutions if this issue cannot be solved. Can there be an easy fix?

**Comment by ThematicaDigital** [comment]
> Going to mark this as closed since the solution is to upgrade to XCode 10.2

And if i can't upgrade Xcode to 10.2 version, cause High Sierra not support this, what can i do?
And yes, i cant upgrade OS, cause device not support 10.14 Mojave.

**Comment by rkotzy** [comment]
The new Apple StoreKit functionality is only available on the latest version of XCode. The easy fix is to use an older version of the Unity SDK .

**Comment by Bfgeshka** [comment]
Older SDK versions aren't working properly.
