### ISSUE TITLE
MacOS Standalone Incompatibility. GetOfferings() does not return

### ISSUE THREAD

**Issue by pshannon1000** [RevenueCat/purchases-unity#16]
Hello,
Trying to get RevenueCat up and running in the Unity Editor on MacOS 10.15.

I'm running the sample files exactly as described in the Documentation, on two singleton GameObjects - with all my API key and identifiers correctly entered in Properties.

- The GetOfferings() function called from PurchasesListener on Line 26 never returns a value.

When I look over in PurchasesListener, I can see that the GetOfferings() function being called on MacOS is inside PurchasesWrapperNoop, and it is an empty function  - Line 151.  (So it makes some sense that nothing is happening.)

How can I get this to work?  Does the GetOfferings() function inside the wrapper in Purchases.cs need to be filled out?

Thank you

**Comment by vegaro** [comment]
Our SDK won't run in the Editor since the APIs we use for IAPs are not available. 

I have identified though that our SDK is not compatible with a MacOS Standalone build at the moment and we are investigating what the best approach is.

**Comment by pshannon1000** [comment]
Had just sent you an email - obviously this does answer it, so no need to respond to the other one.


I am on a tight deadline with the new version of my app in Unity, which is expected by users on MacOS standalone (as well as iOS, Android, and Windows).  (Current MacOS app page: https://apps.apple.com/us/app/seemusic/id1384662993?mt=12 <https://apps.apple.com/us/app/seemusic/id1384662993?mt=12>)


I know that the release of an independent MacOS standalone app probably isn’t anyone’s priority, but if there’s any way to get RevenueCat up and running in my app in the immediate future, it would be very, very much appreciated.

Thank you,
Peter

**Comment by pshannon1000** [comment]
Thank you.

It looks like Windows standalone is processed through the same wrapper as MacOS standalone in Purchases.cs.

Could you confirm if Windows Standalone is supported through the Unity SDK?

**Comment by vegaro** [comment]
Windows is not compatible since we are only compatible with Apple App Store and Google Play Store at the moment. 

I have been spending some hours now trying to get the MacOS Standalone to build but I can't get Unity to find the SDK functions. I have to leave this on the side for now since it looks like it's a bigger challenge than I thought it would be and have other things I have to take care of, but I will come back in the future to see if we can offer support for MacOS builds. I will keep rename this issue and keep it open to keep track of it. Sorry for the trouble.

**Comment by pshannon1000** [comment]
Thanks very much for the clarifications, and for the time spent!

For the time being, I'll just use traditional IAP in my app, so no pressure from my end.  I appreciate the effort though, and I'll check back to see if I can use RevenueCat in the future.

**Comment by aboedo** [comment]
I'm closing this issue for now, since it's been inactive for quite some time, and we're trying to reserve GitHub Issues for bug reports. However taking another look to see if we can support MacOS builds for Unity is in our backlog.

**Comment by yosun** [comment]
Should allow for in-editor testing
