### ISSUE TITLE
Unity IAP & RevenueCat conflict ( when building to Android )

### ISSUE THREAD

**Issue by MohHeader** [RevenueCat/purchases-unity#17]
Hello 

I would like to use RevenueCat in observer mode, so I don't want to stop using Unity IAP for processing purchases.

But once I build to Android, I got this issue:
Duplicate class com.android.vending.billing.IInAppBillingService found in modules classes.jar (:GoogleAIDL:) and classes.jar (com.android.billingclient:billing:2.0.3)
Duplicate class com.android.vending.billing.IInAppBillingService$Stub found in modules classes.jar (:GoogleAIDL:) and classes.jar (com.android.billingclient:billing:2.0.3)
Duplicate class com.android.vending.billing.IInAppBillingService$Stub$Proxy found in modules classes.jar (:GoogleAIDL:) and classes.jar (com.android.billingclient:billing:2.0.3)

due to a duplicate class: com.android.billingclient
I think it can be easily fixed by editing the Gradle file, but if there is an option to do it from RevenueCat itself, it will be much cleaner.

Thanks

**Comment by MohHeader** [comment]
The other option I have is to use RevenuCat Rest API
https://docs.revenuecat.com/reference

**Comment by vegaro** [comment]
If using RevenueCat alongside Unity IAP or other plugin that includes the Android InAppBillingService class, use `Purchases_NoInAppBillingService.unitypackage` version of the package. This version doesn't include the PlayServiceResolver plugin and uses a modified version of BillingClient that doesn't include the IInAppBillingService.

Sorry this fell through the cracks and took so long to reply.
