### ISSUE TITLE
XCode build issue: Value for swift_version cannot be empty

### ISSUE THREAD

**Issue by atelyk** [RevenueCat/purchases-unity#30]
After update to the latest RevenuCat SDK (2.3.0) started receiving a warning on the XCode project opening and build error.
**Value for swift_version cannot be empty**
Since the only swift file used in the project is Dummy.swift, assume this inconvenience is connected with the last update.

Build Platform: iOS
SDK version: 2.3.0
Xcode version: 11.7

The workaround for that is to specify Swift Compiler - Language -> Swift Language Version in Build Settings of the XCode project. But it's required to be done with each new build.

**Comment by aboedo** [comment]
I noticed that too. I'm not sure there's anything that we can do plugin-side, but I'm still researching. 
In the meantime, I think this workaround might help you: https://forum.unity.com/threads/solved-cloud-build-fails-when-using-postprocessbuild.956397/#post-6234828

**Comment by aboedo** [comment]
@atelyk I updated our Subtester app to the latest Unity version and it now correctly sets the value for Swift version. 
https://github.com/RevenueCat/purchases-unity/pull/32
I'd recommend doing the same on your app.

**Comment by atelyk** [comment]
**CARE:** Check additionally if you have set up in the Build Settings **Runpath Search Paths** =`@executable_path/Frameworks` since without it there may be crashes on iOS devices below iOS 12.3:
`Dyld Message: Library not loaded: @rpath/libswiftCore.dylib`

**Comment by aboedo** [comment]
thanks for posting here as well @atelyk!
