### ISSUE TITLE
What about other Apple Platforms? MacOS/TVOS

### ISSUE THREAD

**Issue by voody2506** [RevenueCat/purchases-unity#311]
Hi, do you have plans to support MacOS and TVOS?
I am asking because https://github.com/RevenueCat/purchases-ios supported it and Unity plugin based on native purchases-ios SDK

**Comment by vegaro** [comment]
We don't currently support MacOS, but TVOS should be supported since the code is the same as for an iOS app. Did you have issues with TVOS?

**Comment by voody2506** [comment]
Hi @vegaro, I haven't tested the app on tvOS yet. Does it support M1-based Macs that can run iPad versions?

**Comment by vegaro** [comment]
That should work yes @voody2506 . You can test that by opening the iOS xcode project and running it with Catalyst
