### ISSUE TITLE
productIdentifier null or empty in Purchases.PurchasePackage callback

### ISSUE THREAD

**Issue by Nyankoo** [RevenueCat/purchases-unity#61]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-unity/blob/main/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-unity/issues)

**Describe the bug**
SDK version 3.3 and 3.4 returns null or an empty string for `productIdentifier` in the `Purchases.PurchasePackage` callback.
Version 3.2 is working as expected.

1. Environment
   1. Platform: Unity
   2. SDK version: 3.3 & 3.4
   3. OS + version: Android
   4. Xcode/Android Studio version: Unity
   5. Unity version: 2020.3.9f1
   6. How widespread is the issue. Percentage of devices affected. 100%
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by vegaro** [comment]
The fix has been released https://github.com/RevenueCat/purchases-unity/releases/tag/3.4.1
