### ISSUE TITLE
Random login errors

### ISSUE THREAD

**Issue by aliasifmoneyprep** [RevenueCat/purchases-unity#68]
- [1] I have updated Purchases SDK to the latest version
- [1] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-unity/blob/main/CONTRIBUTING.md)
- [1] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [1] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [1] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-unity/issues)

few of users are getting login errors on different devices and platforms. if there a way to avoid that or get more information about the error

1. Environment
   1. Platform: Android/IOS
   2. SDK version: 3.4.1 
   3. OS + version: Android OS 8.0.0 / API-26 (HUAWEIRNE-L21/348(C185))   // iOS 14.6
   4. Xcode/Android Studio version:
   5. Unity version: 2019.4.30 
   6. How widespread is the issue. Percentage of devices affected. Not a widespread issue but this regression popups after every few days on my Sentry tracking
   
   
![Capture](https://user-images.githubusercontent.com/67921224/134560703-fcd453bf-ef20-49bc-b01b-15c1c6869cb4.PNG)

**Comment by aboedo** [comment]
hi!! 👋  thanks for reporting! I'm going to dig in deeper to see if I can reproduce.

**Comment by vegaro** [comment]
@aliasifmoneyprep We send that error `NetworkError` when there's no connectivity and we have trouble performing requests. This could happen when airplane mode is on, or the internet connectivity of the device is not good. 

Are you getting exceptions? Or are you just logging the error you receive when calling LogIn?

**Comment by aliasifmoneyprep** [comment]
@vegaro  Thanks for the explaination. However, I log in the user with their unique id after they have successfully logged into their account (into our server). which requires internet access and a stable network. 

Users are getting this error randomly. I was able to track this error because it was reported by the Sentry API I am using to track errors in production.

I am closing this thread because it's not game-breaking or happening occasionally but something to look into.
