### ISSUE TITLE
Trying to understand entitlements - Not a bug

### ISSUE THREAD

**Issue by aliasifmoneyprep** [RevenueCat/purchases-unity#70]
1. Environment
   1. Platform: Unity
   2. SDK version: 3.4.1
   3. OS + version:
   4. Xcode/Android Studio version:
   5. Unity version: 2019.4.30
   6. How widespread is the issue. Percentage of devices affected.

So we are facing a weird edge case in the app.

Two months ago I created an entitlement "monthlysub"  and assigned two products "monthlysub" from apple and "monthysub" from google play store (I know the naming convention is not ideal).
So a user purchased the subscription "monthlysub" and cancelled it later on.

Now we decided to create a new product for specific users with 30 days trial. We decided to name the new product "amplimontlysub"  on both apple and google platforms.
Next, I decided to add these products under the already exiting "monthlysub" entitlement. So now " monthlysub" entitlement has a total of four products.
Now when an old user who purchased two months ago but cancelled it decide to subscribe to  "amplimontlysub" product and the transactions from the apple side go thru, the transaction is done I see a pop from apple "you are all set" then I get an error from revenuecat that "there is already another active subscriber using the same receipt".

How do I handle this? we want to offer a different subscription to a few specific users who signup for the app using a promocode.

Is it because the entitlement is same for all 4 products?

**Comment by JazmineMT** [comment]
Hi @aliasifmoneyprep, 

We reserve our Github issues for bugs found in our SDKs. This type of question would be great for your community where a support engineer can assist you. You can ask this question here: https://community.revenuecat.com/. 

Thanks and have a great week!
