### ISSUE TITLE
Unity PostProcessBuild scripts for Xcode

### ISSUE THREAD

**Issue by yosun** [RevenueCat/purchases-unity#72]
This additional step can be omitted with [Unity PostProcessBuild scripts](https://docs.unity3d.com/ScriptReference/Callbacks.PostProcessBuildAttribute.html) "On iOS, add StoreKit.framework to Linked Frameworks and Libraries in Xcode."

**Comment by aboedo** [comment]
Hi! Thanks for opening! That's a great suggestion.
I wasn't aware of this but it seems super useful! 
I'm adding a link to an example gist I found for future reference and to illustrate the idea. https://gist.github.com/kinifi/1cc46b1bfb37219394e0b61a26dd6d4b

**Comment by aboedo** [comment]
Update here: I implemented it in https://github.com/RevenueCat/purchases-unity/pull/85. It'll make it into the next release.

Thanks @yosun for the awesome suggestion!
