### ISSUE TITLE
Unable to distribute to App Store Connect, Invalid bundle

### ISSUE THREAD

**Issue by melih-veloxia** [RevenueCat/purchases-unity#82]
- [ ✅ ] I have updated Purchases SDK to the latest version
- [ ✅ ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-unity/blob/main/CONTRIBUTING.md)
- [ ✅ ] I have searched the [Community](https://community.revenuecat.com)
- [ ✅ ] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ ✅ ] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-unity/issues)

Starting from 2020x, Unity introduced a new standard for Unity's iOS builds wherein plugins and files are contained within UnityFramework.framework (which is where I see RevenueCat’s generated code and other files). That's why when we try to upload our binary with RevenueCat to Apple Store Connect through Xcode, we get the error: ERROR ITMS-90206: "Invalid Bundle. The bundle at 'APPNAME.app/Frameworks/UnityFramework.framework' contains disallowed file 'Frameworks'.". Before installing RevenueCat, there wasn't any problem.

1. Environment
   1. Platform: iOS
   2. SDK version: 3.5.0
   3. OS + version: MacOS 11.3.1
   4. Xcode/Android Studio version: 12.5.1
   5. Unity version: 2020.3.25f1
   6. How widespread is the issue. Percentage of devices affected: 100% 

2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
   None

3. Steps to reproduce, with a description of expected vs. actual behavior
    1. Build to Xcode with Unity 2020.3.25f1 after RevenueCat installation
    2. Archive the build
    3. Try to distribute to App Store Connect 

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
  As a workaround, one may follow the steps below:
    1. Build project to Xcode from Unity like you normally would
    2. In the project view, select the target that is your project (usually called "Unity-IPhone" from what I've seen)
    3. Click Build Phases
    4. Click that small plus sign that’s really easy to miss at the top of the build phases section of Xcode
    5. Choose New Run Script Phase
    6. Expand the newly added Run Script
    7. Paste this script in there: 
  `cd "${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/Frameworks/UnityFramework.framework/"
if [[ -d "Frameworks" ]]; then
    rm -fr Frameworks
fi`

**Additional context**
These additional steps prevent us to use our CI/CD pipeline, that’s why an immediate fix is required.

References:
https://developer.apple.com/forums/thread/654980
https://support.wikitude.com/support/discussions/topics/5000096581

**Comment by melih-veloxia** [comment]
I haven't skipped any required information, only some whitespaces to increase the readability.

**Comment by aboedo** [comment]
hi @melih-veloxia! Thanks for reporting! Sorry about the bot, the ticket is fine. 
I'm gonna dig into this and report back

**Comment by aboedo** [comment]
I can confirm that with Unity `2020.3.27f1`, I am able to reproduce the error when validating a build of our [Unity Subtester app](https://github.com/RevenueCat/purchases-unity/tree/main/Subtester) with Organizer. 

I'm a curious, though, about the setup that led to the .framework being there. 
We use Cocoapods to distribute our .framework with Unity, through the [External Dependency Manager](https://github.com/googlesamples/unity-jar-resolver). 

Cocoapods doesn't actually create a `Frameworks` folder, it instead just creates a single, [static library that embeds all frameworks](https://guides.cocoapods.org/using/using-cocoapods.html#what-is-happening-behind-the-scenes). 

You can even see this in the project's build phases.

I believe you're correct in the problem being a change in Unity. I don't think that it's entirely related to our SDK, although I'm still investigating and not discarding the possibility. 

I'll report back when I know more. 

Thanks again for reporting!

**Comment by melih-veloxia** [comment]
@aboedo Thanks for your quick reply. Just like I said, we use bunch of other SDKs with cocoapods through EDM4U and without RevenueCat, there isn't any problem.

**Comment by aboedo** [comment]
@melih-veloxia that's good to know. Could you provide a couple of examples of the SDKs that you have through cocoapods that do work with no problem, so I can try to see what they're doing differently?

**Comment by aboedo** [comment]
Thanks!! I'll take a look

**Comment by aboedo** [comment]
@melih-veloxia I made a PR for the fix, #84. 
The PR adds a post install script that will ensure that `ALWAYS_EMBED_SWIFT_LIBRARIES` is set to `NO`. 

It'll make it into a release soon. 

In the meantime, you can also solve this for your project by clicking on the target in the Xcode project, then looking for `ALWAYS_EMBED_SWIFT_LIBRARIES` and setting it to `NO` (you may need to do it for other targets too). 

I tried it in the same app that I used to reproduce the issue and the issue was gone. 

<img width="877" alt="image" src="https://user-images.githubusercontent.com/3922667/152426029-7f356f4b-34e4-4640-9e87-a68ab725d7a5.png">

Hope this helps!! Thanks again for reporting and for being so responsive!

**Comment by melih-veloxia** [comment]
Hey @aboedo! Thanks, will give it a try with the pull request and let you know! Thanks for the quick solution.

**Comment by melih-veloxia** [comment]
I merged your 2 pull requests into our project and it works with the CI/CD pipeline! 

Closing the issue right now, thanks for your cooperation.

**Comment by aboedo** [comment]
Thanks for the confirmation @melih-veloxia!!! I'll be making an official release with both PRs today. Let us know if you run into any more issues!
