### ISSUE TITLE
RevenueCat Purchases SDK doesn't get initialized

### ISSUE THREAD

**Issue by YigitVeloxia** [RevenueCat/purchases-unity#83]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-unity/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-unity/issues)

**Describe the bug**
RevenueCat doesn't get initialized because it can't find com/revenuecat/purchases/google/BillingWrapper class

1. Environment
   1. Platform: Android
   2. SDK version: 3.5.0
   3. OS + version: Android 11
   4. Xcode/Android Studio version:
   5. Unity version: Unity 2020.3.25f1
   6. How widespread is the issue. Percentage of devices affected. 100%
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
```2022/02/03 15:02:44.221 9309 14594 Error Unity AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/revenuecat/purchases/google/BillingWrapper;
2022/02/03 15:02:44.221 9309 14594 Error Unity java.lang.NoClassDefFoundError: Failed resolution of: Lcom/revenuecat/purchases/google/BillingWrapper;
2022/02/03 15:02:44.221 9309 14594 Error Unity     at com.revenuecat.purchases.BillingFactory.createBilling(BillingFactory.kt:22)
2022/02/03 15:02:44.221 9309 14594 Error Unity     at com.revenuecat.purchases.Purchases$Companion.configure$purchases_release(Purchases.kt:1874)
2022/02/03 15:02:44.221 9309 14594 Error Unity     at com.revenuecat.purchases.Purchases$Companion.configure(Purchases.kt:1828)
2022/02/03 15:02:44.221 9309 14594 Error Unity     at com.revenuecat.purchases.Purchases$Companion.configure$default(Purchases.kt:1821)
2022/02/03 15:02:44.221 9309 14594 Error Unity     at com.revenuecat.purchases.hybridcommon.CommonKt.configure(common.kt:329)
2022/02/03 15:02:44.221 9309 14594 Error Unity     at com.revenuecat.purchasesunity.PurchasesWrapper.setup(PurchasesWrapper.java:66)
2022/02/03 15:02:44.221 9309 14594 Error Unity     at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2022/02/03 15:02:44.221 9309 14594 Error Unity     at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
2022/02/03 15:02:44.221 9309 14594 Error Unity     at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
2022/02/03 15:02:44.221 9309 14594 Error Unity     at android.os.Handler.dispatchMessage(Handler.java:102)
2022/02/03 15:02:44.221 9309 14594 Error Unity     at android.os.Looper.loopOnce(Looper.ja
2022/02/03 15:02:44.229 9309 14594 Error Unity AndroidJavaException: kotlin.UninitializedPropertyAccessException: There is no singleton instance. Make sure you configure Purchases before trying to get the default instance. More info here: https://errors.rev.cat/configuring-sdk
2022/02/03 15:02:44.229 9309 14594 Error Unity kotlin.UninitializedPropertyAccessException: There is no singleton instance. Make sure you configure Purchases before trying to get the default instance. More info here: https://errors.rev.cat/configuring-sdk
2022/02/03 15:02:44.229 9309 14594 Error Unity     at com.revenuecat.purchases.Purchases$Companion.getSharedInstance(Purchases.kt:1775)
2022/02/03 15:02:44.229 9309 14594 Error Unity     at com.revenuecat.purchases.hybridcommon.CommonKt.getOfferings(common.kt:44)
2022/02/03 15:02:44.229 9309 14594 Error Unity     at com.revenuecat.purchasesunity.PurchasesWrapper.getOfferings(PurchasesWrapper.java:199)
2022/02/03 15:02:44.229 9309 14594 Error Unity     at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2022/02/03 15:02:44.229 9309 14594 Error Unity     at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
2022/02/03 15:02:44.229 9309 14594 Error Unity     at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
2022/02/03 15:02:44.229 9309 14594 Error Unity     at android.os.Handler.dispatchMessage(Handler.java:102)
2022/02/03 15:02:44.229 9309 14594 Error Unity     at android.os.Looper.loopOnce(Looper.java:226)
2022/02/03 15:02:44.229 9309 14594 Error Unity     at android.os.Looper.lo
```

3. Steps to reproduce, with a description of expected vs. actual behavior
Just install the SDK and build for an Android device.

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
We don't use Unity IAP package. Only RevenueCat is on the project currently.

**Additional context**

**Comment by vegaro** [comment]
@YigitVeloxia what's your setup regarding dependencies? Do you use EDM4U? Do you have a `mainTemplate.gradle` in yout project?

**Comment by melih-veloxia** [comment]
@vegaro You may find the mainTemplate.gradle file:
`
// Android Resolver Repos Start
([rootProject] + (rootProject.subprojects as List)).each { project ->
    project.repositories {
        def unityProjectPath = $/file:///**DIR_UNITYPROJECT**/$.replace("\\", "/")
        maven {
            url "https://maven.google.com"
        }
        maven {
            url (unityProjectPath + "/Assets/GeneratedLocalRepo/Firebase/m2repository") // Assets/Firebase/Editor/AnalyticsDependencies.xml:18, Assets/Firebase/Editor/AppDependencies.xml:22, Assets/Firebase/Editor/CrashlyticsDependencies.xml:20, Assets/Firebase/Editor/MessagingDependencies.xml:22, Assets/Firebase/Editor/RemoteConfigDependencies.xml:20
        }
        maven {
            url (unityProjectPath + "/Assets/GeneratedLocalRepo/GooglePlayGames/Editor/m2repository") // Assets/GooglePlayGames/Editor/GooglePlayGamesPluginDependencies.xml:11
        }
        maven {
            url "https://android-sdk.is.com/" // Assets/IronSource/Editor/IronSourceSDKDependencies.xml:8, Assets/IronSource/Editor/ISAdMobAdapterDependencies.xml:16, Assets/IronSource/Editor/ISFacebookAdapterDependencies.xml:16, Assets/IronSource/Editor/ISTapJoyAdapterDependencies.xml:8, Assets/IronSource/Editor/ISUnityAdsAdapterDependencies.xml:8, Assets/IronSource/Editor/ISVungleAdapterDependencies.xml:16
        }
        maven {
            url "https://maven.google.com/" // Assets/IronSource/Editor/IronSourceSDKDependencies.xml:16, Assets/IronSource/Editor/IronSourceSDKDependencies.xml:24, Assets/IronSource/Editor/IronSourceSDKDependencies.xml:32, Assets/IronSource/Editor/ISAdMobAdapterDependencies.xml:8, Assets/IronSource/Editor/ISFacebookAdapterDependencies.xml:8, Assets/IronSource/Editor/ISUnityAdsAdapterDependencies.xml:15
        }
        maven {
            url "https://sdk.tapjoy.com/" // Assets/IronSource/Editor/ISTapJoyAdapterDependencies.xml:15
        }
        maven {
            url "https://jitpack.io/" // Assets/IronSource/Editor/ISVungleAdapterDependencies.xml:8
        }
        mavenLocal()
        mavenCentral()
    }
}
// Android Resolver Repos End
apply plugin: 'com.android.library'
**APPLY_PLUGINS**

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    configurations.all {
        exclude group: 'com.android.billingclient', module: 'billing'
    }
// Android Resolver Dependencies Start
    implementation 'androidx.annotation:annotation:[1.2.0]' // Assets/RevenueCat/Plugins/Editor/RevenueCatDependencies.xml:5
    implementation 'androidx.multidex:multidex:2.0.1' // Assets/Editor/SCIDependencies.xml:4
    implementation 'com.android.installreferrer:installreferrer:2.1' // Assets/AppsFlyer/Editor/AppsFlyerDependencies.xml:10
    implementation 'com.android.support:appcompat-v7:25.3.1' // Facebook.Unity.Editor.AndroidSupportLibraryResolver.addSupportLibraryDependency
    // implementation 'com.android.support:cardview-v7:[26.0.0, 27.2.0[' // Packages/com.onesignal.unity.android/Editor/OneSignalDependencies.xml:7
    implementation 'com.android.support:cardview-v7:25.3.1' // Facebook.Unity.Editor.AndroidSupportLibraryResolver.addSupportLibraryDependency
    // implementation 'com.android.support:customtabs:[26.0.0, 27.2.0[' // Packages/com.onesignal.unity.android/Editor/OneSignalDependencies.xml:8
    implementation 'com.android.support:customtabs:25.3.1' // Facebook.Unity.Editor.AndroidSupportLibraryResolver.addSupportLibraryDependency
    // implementation 'com.android.support:support-v4:[26.0.0, 27.2.0[' // Packages/com.onesignal.unity.android/Editor/OneSignalDependencies.xml:6
    implementation 'com.android.support:support-v4:25.3.1' // Facebook.Unity.Editor.AndroidSupportLibraryResolver.addSupportLibraryDependency
    implementation 'com.appsflyer:af-android-sdk:6.3.2' // Assets/AppsFlyer/Editor/AppsFlyerDependencies.xml:6
    implementation 'com.appsflyer:unity-wrapper:6.3.2' // Assets/AppsFlyer/Editor/AppsFlyerDependencies.xml:8
    implementation 'com.facebook.android:audience-network-sdk:6.8.0' // Assets/IronSource/Editor/ISFacebookAdapterDependencies.xml:8
    implementation 'com.facebook.android:facebook-applinks:[11.0, 12)' // Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:6
    implementation 'com.facebook.android:facebook-core:[11.0, 12)' // Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:5
    implementation 'com.facebook.android:facebook-gamingservices:[11.0, 12)' // Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:9
    implementation 'com.facebook.android:facebook-login:[11.0, 12)' // Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:7
    implementation 'com.facebook.android:facebook-share:[11.0, 12)' // Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:8
    implementation 'com.google.android.gms:play-services-ads:20.5.0' // Assets/IronSource/Editor/ISAdMobAdapterDependencies.xml:8
    implementation 'com.google.android.gms:play-services-ads-identifier:17.0.0' // Assets/IronSource/Editor/IronSourceSDKDependencies.xml:16
    implementation 'com.google.android.gms:play-services-appset:16.0.0' // Assets/IronSource/Editor/IronSourceSDKDependencies.xml:24
    // implementation 'com.google.android.gms:play-services-base:[10.2.1, 12.1.0[' // Packages/com.onesignal.unity.android/Editor/OneSignalDependencies.xml:3
    implementation 'com.google.android.gms:play-services-base:17.6.0' // Assets/Firebase/Editor/AppDependencies.xml:17
    implementation 'com.google.android.gms:play-services-basement:17.2.1' // Assets/IronSource/Editor/IronSourceSDKDependencies.xml:32
    implementation 'com.google.android.gms:play-services-location:[10.2.1, 12.1.0[' // Packages/com.onesignal.unity.android/Editor/OneSignalDependencies.xml:5
    implementation 'com.google.firebase:firebase-analytics:19.0.0' // Assets/Firebase/Editor/RemoteConfigDependencies.xml:15
    implementation 'com.google.firebase:firebase-analytics-unity:8.2.0' // Assets/Firebase/Editor/AnalyticsDependencies.xml:18
    implementation 'com.google.firebase:firebase-app-unity:8.2.0' // Assets/Firebase/Editor/AppDependencies.xml:22
    implementation 'com.google.firebase:firebase-common:20.0.0' // Assets/Firebase/Editor/AppDependencies.xml:13
    implementation 'com.google.firebase:firebase-config:21.0.0' // Assets/Firebase/Editor/RemoteConfigDependencies.xml:13
    implementation 'com.google.firebase:firebase-config-unity:8.2.0' // Assets/Firebase/Editor/RemoteConfigDependencies.xml:20
    implementation 'com.google.firebase:firebase-crashlytics:18.0.1' // Assets/Firebase/Editor/CrashlyticsDependencies.xml:13
    implementation 'com.google.firebase:firebase-crashlytics-unity:8.2.0' // Assets/Firebase/Editor/CrashlyticsDependencies.xml:20
    implementation 'com.google.firebase:firebase-iid:21.1.0' // Assets/Firebase/Editor/MessagingDependencies.xml:17
    // implementation 'com.google.firebase:firebase-messaging:[10.2.1, 12.1.0[' // Packages/com.onesignal.unity.android/Editor/OneSignalDependencies.xml:4
    implementation 'com.google.firebase:firebase-messaging:22.0.0' // Assets/Firebase/Editor/MessagingDependencies.xml:13
    implementation 'com.google.firebase:firebase-messaging-unity:8.2.0' // Assets/Firebase/Editor/MessagingDependencies.xml:22
    implementation 'com.google.games:gpgs-plugin-support:0.10.11' // Assets/GooglePlayGames/Editor/GooglePlayGamesPluginDependencies.xml:11
    implementation 'com.ironsource.adapters:admobadapter:4.3.24' // Assets/IronSource/Editor/ISAdMobAdapterDependencies.xml:16
    implementation 'com.ironsource.adapters:facebookadapter:4.3.33' // Assets/IronSource/Editor/ISFacebookAdapterDependencies.xml:16
    implementation 'com.ironsource.adapters:tapjoyadapter:4.1.19' // Assets/IronSource/Editor/ISTapJoyAdapterDependencies.xml:8
    implementation 'com.ironsource.adapters:unityadsadapter:4.3.16' // Assets/IronSource/Editor/ISUnityAdsAdapterDependencies.xml:8
    implementation 'com.ironsource.adapters:vungleadapter:4.3.12' // Assets/IronSource/Editor/ISVungleAdapterDependencies.xml:16
    implementation 'com.ironsource.sdk:mediationsdk:7.1.12.2' // Assets/IronSource/Editor/IronSourceSDKDependencies.xml:8
    implementation 'com.parse.bolts:bolts-android:1.4.0' // Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:4
    implementation 'com.revenuecat.purchases:purchases-hybrid-common:[1.10.0]' // Assets/RevenueCat/Plugins/Editor/RevenueCatDependencies.xml:4
    implementation 'com.tapjoy:tapjoy-android-sdk:12.8.1@aar' // Assets/IronSource/Editor/ISTapJoyAdapterDependencies.xml:15
    implementation 'com.unity3d.ads:unity-ads:3.7.5' // Assets/IronSource/Editor/ISUnityAdsAdapterDependencies.xml:15
    implementation 'com.vungle:publisher-sdk-android:6.10.2' // Assets/IronSource/Editor/ISVungleAdapterDependencies.xml:8
// Android Resolver Dependencies End
**DEPS**}

// Android Resolver Exclusions Start
android {
  packagingOptions {
      exclude ('/lib/armeabi/*' + '*')
      exclude ('/lib/mips/*' + '*')
      exclude ('/lib/mips64/*' + '*')
      exclude ('/lib/x86/*' + '*')
      exclude ('/lib/x86_64/*' + '*')
  }
}
// Android Resolver Exclusions End
android {
    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
        consumerProguardFiles 'proguard-unity.txt'**USER_PROGUARD**
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = ['.ress', '.resource', '.obb'] + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~"
    }**PACKAGING_OPTIONS**
}**REPOSITORIES**
**IL_CPP_BUILD_SETUP**
**SOURCE_BUILD_SETUP**
**EXTERNAL_SOURCES**
`

**Comment by vegaro** [comment]
Thanks for sending that over. I see you are doing:

```
    configurations.all {
        exclude group: 'com.android.billingclient', module: 'billing'
    }
```

Is there a reason why you do that? We recommend doing that only when using our SDK and Unity IAP at the same time. 

I believe that configuration is what's causing you trouble. Can you try removing that and reporting back? Thanks!

**Comment by YigitVeloxia** [comment]
Thanks, removing that fixed the issue. I think it was a leftover from the last try of our installation.
