### ISSUE TITLE
Crash when not setting `deprecatedLegacyRevenueCatAPIKey` on simulator

### ISSUE THREAD

**Issue by aboedo** [RevenueCat/purchases-unity#89]
On 3.5.0 and 3.5.1 versions of purchases-unity, if you test using the simulator, the app will crash with a confusing message saying "Unity error: "NullReferenceException: Object reference not set to an instance of an object". 

The issue stems [from this logic in `setup`](https://github.com/RevenueCat/purchases-unity/blob/main/RevenueCat/Scripts/Purchases.cs#L105), which checks for iOS and Android physical devices, but apparently simulators don't pass the checks.

**Comment by beylmk** [comment]
@aboedo i was somehow able to run on a simulator with just the "appl_" key defined. i tried on a few different simulators running ios 15.2.. do you have more info on the simulator you tried? or was this android?

**Comment by aboedo** [comment]
it was Android, yeah. It came from a ZenDesk ticket

**Comment by beylmk** [comment]
ahhhh okay. i'm so used to "emulator" for android that i somehow just assumed this was ios. thank you!
